steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:${$TAG_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:${$TAG_NAME}']
images: ['gcr.io/$PROJECT_ID/frontend:${$TAG_NAME}']
