steps:
#deploy
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - apply
  - -f
  - kubernetes-manifests.yaml
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_LOCATION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
