steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:gitlab', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:gitlab']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=depl.yaml
  - --image=gcr.io/$PROJECT_ID/frontend:gitlab
  - --location=${_LOCATION}
  - --cluster=${_CLUSTER}
images: ['gcr.io/$PROJECT_ID/frontend:gitlab']
